# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f84ce61dbf3e96f127b86517825eca985194e7ca1bb9139754e02bbedd71c4c1e5f02f25094ed6aa85a03b6fee6b0d70ee1bb20cd4114c20e33d1b95e2c4f7b2

test:
  secret_key_base: 80d026e07abcf7d3f9a0e3b0c01358eca97a8d870b3dcec27ecd6125a73ba5cfc7d539b1b607d31d80db658f5c1a34275d3644bbdb1896f600e2072a2de7fec0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
